#!/bin/sh
CUDA=0
ORDER=1

CUDA_VISIBLE_DEVICES=$CUDA python main.py --order $ORDER --dataset_path ~/dataset/ --dataset split_mnist --n_task 5 --n_epoch1t 500 --n_epoch 500 --batch_size 32 --learning_rate 0.001 --model MLP --hidden_dim 100 --n_hidden_layer 4 --method sgd
#CUDA_VISIBLE_DEVICES=$CUDA python main.py --order $ORDER --dataset_path ~/dataset/ --dataset split_mnist --n_task 5 --n_epoch1t 500 --n_epoch 500 --batch_size 32 --learning_rate 0.001 --model MLP --hidden_dim 100 --n_hidden_layer 4 --method ewc --ewc_method sma --fisher_sample 2000 --ema_constant 50
#CUDA_VISIBLE_DEVICES=$CUDA python main.py --order $ORDER --dataset_path ~/dataset/ --dataset split_mnist --n_task 5 --n_epoch1t 500 --n_epoch 500 --batch_size 32 --learning_rate 0.001 --model MLP --hidden_dim 100 --n_hidden_layer 4 --method agem --n_examplar 100
#CUDA_VISIBLE_DEVICES=$CUDA python main.py --order $ORDER --dataset_path ~/dataset/ --dataset split_mnist --n_task 5 --n_epoch1t 500 --n_epoch 500 --batch_size 32 --learning_rate 0.001 --model MLP --hidden_dim 100 --n_hidden_layer 4 --method ogd --n_basis 100
#CUDA_VISIBLE_DEVICES=$CUDA python main.py --order $ORDER --dataset_path ~/dataset/ --dataset split_mnist --n_task 15 --n_epoch1t 500 --n_epoch 500 --batch_size 32 --learning_rate 0.001 --model MLP --hidden_dim 100 --n_hidden_layer 4 --method pca_ogd --n_basis 100 --n_sample 2000
#CUDA_VISIBLE_DEVICES=$CUDA python main.py --order $ORDER --dataset_path ~/dataset/ --dataset permuted_mnist --n_task 15 --n_epoch1t 500 --n_epoch 500 --batch_size 32 --learning_rate 0.001 --model MLP --hidden_dim 100 --n_hidden_layer 4 --method pca_ogd --n_basis 100 --n_sample 10000
#CUDA_VISIBLE_DEVICES=$CUDA python main.py --order $ORDER --dataset_path ~/dataset/CIFAR/ --dataset split_cifar --n_task 20 --n_epoch1t 500 --n_epoch 500 --batch_size 32 --learning_rate 0.001 --model Lenet --hidden_dim 200 --n_hidden_layer 1 --conv1_channel 20 --conv2_channel 50 --method pca_ogd --n_basis 100 --n_sample 2500
#CUDA_VISIBLE_DEVICES=$CUDA python main.py --order $ORDER --dataset_path ~/dataset/ --dataset split_mnist --n_task 15 --n_epoch1t 500 --n_epoch 500 --batch_size 32 --learning_rate 0.001 --model MLP --hidden_dim 100 --n_hidden_layer 4 --method train_basis --n_basis 100 --n_sample 128 --perturb_distance 0.5 --learning_rate_u 0.0001 --lambda_distance 10000 --lambda_orthogonal 100
#CUDA_VISIBLE_DEVICES=$CUDA python main.py --order $ORDER --dataset_path ~/dataset/ --dataset permuted_mnist --n_task 15 --n_epoch1t 500 --n_epoch 500 --batch_size 32 --learning_rate 0.001 --model MLP --hidden_dim 100 --n_hidden_layer 4 --method train_basis --n_basis 100 --n_sample 128 --perturb_distance 0.5 --learning_rate_u 0.0001 --lambda_distance 10000 --lambda_orthogonal 100
#CUDA_VISIBLE_DEVICES=$CUDA python main.py --order $ORDER --dataset_path ~/dataset/CIFAR/ --dataset split_cifar --n_task 20 --n_epoch1t 500 --n_epoch 500 --batch_size 32 --learning_rate 0.001 --model Lenet --hidden_dim 200 --n_hidden_layer 1 --conv1_channel 20 --conv2_channel 50 --method train_basis --n_basis 100 --n_sample 128 --perturb_distance 0.2 --learning_rate_u 0.0001 --lambda_distance 10000 --lambda_orthogonal 10
